services:
  backend:
    container_name: student_stay_backend
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "29595:80"
    networks:
      project_net:
      intern:
        ipv4_address: 192.168.48.12
    restart: unless-stopped


  frontend:
    container_name: student_stay_frontend
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "45637:3000"
    networks:
      project_net:
    restart: unless-stopped

  form_frontend:
    container_name: student_stay_from_frontend
    build: 
      context: ./form_frontend/
      dockerfile: Dockerfile
    ports:
      - "58240:3000"
    networks:
      project_net:
    restart: unless-stopped

networks:
  project_net:
    external: true
  intern:
    external: true